/**
 * Fallback store data when Sanity has no products yet.
 * Modeled after https://www.eaa690.org/store (memberships, food events,
 * memorials, prints, merch, fees, donations).
 */
import type { StoreCategory, StoreProduct } from '@/lib/sanity-types'

const LIVE_STORE = 'https://www.eaa690.org/store'

export const fallbackStoreCategories: StoreCategory[] = [
  { _id: 'fb-cat-memberships', title: 'Memberships', slug: { current: 'memberships' }, sortOrder: 0 },
  { _id: 'fb-cat-summer-camp', title: 'Summer Camp Fees', slug: { current: 'summer-camp' }, sortOrder: 1 },
  { _id: 'fb-cat-food', title: 'Food & Breakfasts', slug: { current: 'food-events' }, sortOrder: 2 },
  {
    _id: 'fb-cat-fundraisers',
    title: 'Fundraisers & Special Dinners',
    slug: { current: 'fundraisers' },
    sortOrder: 3,
  },
  {
    _id: 'fb-cat-memorials',
    title: 'Memorials, Plaques & Scholarships',
    slug: { current: 'memorials' },
    sortOrder: 4,
  },
  { _id: 'fb-cat-art', title: 'Art & Prints', slug: { current: 'art-prints' }, sortOrder: 5 },
  { _id: 'fb-cat-merch', title: 'Chapter Merchandise', slug: { current: 'merchandise' }, sortOrder: 6 },
  { _id: 'fb-cat-fees', title: 'Hangar & Other Fees', slug: { current: 'fees' }, sortOrder: 7 },
  { _id: 'fb-cat-donations', title: 'Donations', slug: { current: 'donations' }, sortOrder: 8 },
]

function cats(...slugs: string[]): StoreCategory[] {
  return fallbackStoreCategories.filter((c) => slugs.includes(c.slug.current))
}

export const fallbackStoreProducts: StoreProduct[] = [
  {
    _id: 'fb-p-1',
    title: 'Spaghetti Dinner',
    slug: { current: 'spaghetti-dinner' },
    priceDisplay: '$15.00',
    shortDescription: 'Chapter fundraiser dinner.',
    categories: cats('fundraisers', 'food-events'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 10,
    isActive: true,
  },
  {
    _id: 'fb-p-2',
    title: 'Donations',
    slug: { current: 'donations' },
    priceDisplay: '$25.00',
    shortDescription: 'Support EAA Chapter 690 programs.',
    categories: cats('donations'),
    externalPurchaseUrl: 'https://www.eaa690.org/store/p/donations',
    sortOrder: 20,
    isActive: true,
  },
  {
    _id: 'fb-p-3',
    title: 'Family Membership',
    slug: { current: 'family-membership' },
    priceDisplay: '$45.00 every 12 months',
    shortDescription: 'Family membership — join or renew.',
    categories: cats('memberships'),
    externalPurchaseUrl: 'https://www.eaa690.org/store/p/family-membership-dMl4c',
    sortOrder: 30,
    isActive: true,
  },
  {
    _id: 'fb-p-4',
    title: 'Individual Membership',
    slug: { current: 'individual-membership' },
    priceDisplay: '$35.00 every 12 months',
    shortDescription: 'Individual membership — join or renew.',
    categories: cats('memberships'),
    externalPurchaseUrl: 'https://www.eaa690.org/store/p/individual-membership-j9am4-vXxPq',
    sortOrder: 40,
    isActive: true,
  },
  {
    _id: 'fb-p-5',
    title: 'Low Country Boil',
    slug: { current: 'low-country-boil' },
    priceDisplay: '$25.00',
    shortDescription: 'Chapter event meal.',
    categories: cats('fundraisers', 'food-events'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 50,
    isActive: true,
  },
  {
    _id: 'fb-p-6',
    title: 'Monthly Pancake Breakfast',
    slug: { current: 'pancake-breakfast' },
    priceDisplay: '$10.00',
    shortDescription: 'First Saturday monthly breakfast.',
    categories: cats('food-events'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 60,
    isActive: true,
  },
  {
    _id: 'fb-p-7',
    title: 'Pancake Breakfast — Children 10 and Under',
    slug: { current: 'pancake-breakfast-children' },
    priceDisplay: '$3.00',
    shortDescription: 'Children’s breakfast pricing.',
    categories: cats('food-events'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 70,
    isActive: true,
  },
  {
    _id: 'fb-p-8',
    title: 'Ken Sharp Memorial Plaque',
    slug: { current: 'ken-sharp-memorial-plaque' },
    priceDisplay: '$25.00',
    shortDescription: 'Memorial plaque — In Memoriam.',
    categories: cats('memorials'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 80,
    isActive: true,
  },
  {
    _id: 'fb-p-9',
    title: 'Kathi Parks Memorial Scholarship',
    slug: { current: 'kathi-parks-memorial-scholarship' },
    priceDisplay: '$25.00',
    shortDescription: 'Scholarship contribution.',
    categories: cats('memorials'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 90,
    isActive: true,
  },
  {
    _id: 'fb-p-10',
    title: 'Sam Lyons Pony Express with Wings — Signed Print',
    slug: { current: 'sam-lyons-pony-express' },
    priceDisplay: '$125.00',
    shortDescription: 'Signed aviation art print.',
    categories: cats('art-prints'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 100,
    isActive: true,
  },
  {
    _id: 'fb-p-11',
    title: 'Sam Lyons Famous Honored Few — Signed Print',
    slug: { current: 'sam-lyons-honored-few' },
    priceDisplay: '$200.00',
    shortDescription: 'Signed aviation art print.',
    categories: cats('art-prints'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 110,
    isActive: true,
  },
  {
    _id: 'fb-p-12',
    title: 'Sam Lyons Checking The Mail — Signed Print',
    slug: { current: 'sam-lyons-checking-the-mail' },
    priceDisplay: '$125.00',
    shortDescription: 'Signed aviation art print.',
    categories: cats('art-prints'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 120,
    isActive: true,
  },
  {
    _id: 'fb-p-13',
    title: 'Sam Lyons Air Assault — Signed Print',
    slug: { current: 'sam-lyons-air-assault' },
    priceDisplay: '$90.00',
    shortDescription: 'Signed aviation art print.',
    categories: cats('art-prints'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 130,
    isActive: true,
  },
  {
    _id: 'fb-p-14',
    title: 'Man on Bicycle BiPlane',
    slug: { current: 'man-on-bicycle-biplane' },
    priceDisplay: '$50.00',
    shortDescription: 'Art print.',
    categories: cats('art-prints'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 140,
    isActive: true,
  },
  {
    _id: 'fb-p-15',
    title: 'Student Membership',
    slug: { current: 'student-membership' },
    priceDisplay: '$10.00',
    shortDescription: 'Student membership — join or renew.',
    categories: cats('memberships'),
    externalPurchaseUrl: 'https://www.eaa690.org/store/p/student-membership',
    sortOrder: 150,
    isActive: true,
  },
  {
    _id: 'fb-p-16',
    title: 'Name Tag',
    slug: { current: 'name-tag' },
    priceDisplay: '$14.00',
    shortDescription: 'Chapter name tag.',
    categories: cats('merchandise'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 160,
    isActive: true,
  },
  {
    _id: 'fb-p-17',
    title: 'In Memoriam',
    slug: { current: 'in-memoriam' },
    priceDisplay: '$25.00',
    shortDescription: 'In Memoriam contribution.',
    categories: cats('memorials'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 170,
    isActive: true,
  },
  {
    _id: 'fb-p-18',
    title: 'Olson Memorial Plaque',
    slug: { current: 'olson-memorial-plaque' },
    priceDisplay: '$25.00',
    shortDescription: 'Memorial plaque.',
    categories: cats('memorials'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 180,
    isActive: true,
  },
  {
    _id: 'fb-p-19',
    title: 'Huff Memorial Plaque',
    slug: { current: 'huff-memorial-plaque' },
    priceDisplay: '$25.00',
    shortDescription: 'Memorial plaque.',
    categories: cats('memorials'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 190,
    isActive: true,
  },
  {
    _id: 'fb-p-20',
    title: 'EAA 690 Mug',
    slug: { current: 'eaa-690-mug' },
    priceDisplay: '$12.00',
    shortDescription: 'Chapter mug.',
    categories: cats('merchandise'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 200,
    isActive: true,
  },
  {
    _id: 'fb-p-21',
    title: 'EAA 690 Coaster Set',
    slug: { current: 'eaa-690-coaster-set' },
    priceDisplay: '$20.00',
    shortDescription: 'Coaster set.',
    categories: cats('merchandise'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 210,
    isActive: true,
  },
  {
    _id: 'fb-p-22',
    title: 'Hangar Use Fee',
    slug: { current: 'hangar-use-fee' },
    priceDisplay: '$10.00',
    shortDescription: 'Hangar use fee.',
    categories: cats('fees'),
    externalPurchaseUrl: LIVE_STORE,
    sortOrder: 220,
    isActive: true,
  },
]
